// <auto-generated />
using System;
using CinemaProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CinemaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211208211627_f1")]
    partial class f1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CinemaProject.Data.Cart", b =>
                {
                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cartId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("createAt");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("date")
                        .HasColumnName("endAt");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("paymentType")
                        .IsFixedLength(true);

                    b.Property<long?>("PromocodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("promocodeId");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int")
                        .HasColumnName("totalPrice");

                    b.HasKey("CartId", "UserId");

                    b.HasIndex("PromocodeId");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("CinemaProject.Data.CartProduct", b =>
                {
                    b.Property<long>("CartProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("cartProductId");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("productId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cartId");

                    b.HasKey("CartProductId", "ProductId", "UserId", "CartId")
                        .HasName("PK_CartProducts_1");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "UserId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("CinemaProject.Data.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .HasColumnName("categoryDescription")
                        .IsFixedLength(true);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("categoryName")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("createAt");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CinemaProject.Data.Cinema", b =>
                {
                    b.Property<long>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cinemaId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength(true);

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("cityId");

                    b.HasKey("CinemaId");

                    b.HasIndex("CityId");

                    b.ToTable("Cinema");
                });

            modelBuilder.Entity("CinemaProject.Data.City", b =>
                {
                    b.Property<long>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("cityId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("cityName")
                        .IsFixedLength(true);

                    b.HasKey("CityId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("CinemaProject.Data.Demonstration", b =>
                {
                    b.Property<long>("DemonstrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("demonstrationId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cof")
                        .HasColumnType("float")
                        .HasColumnName("cof");

                    b.Property<string>("DemonstrationName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("demonstrationName")
                        .IsFixedLength(true);

                    b.HasKey("DemonstrationId");

                    b.ToTable("Demonstration");
                });

            modelBuilder.Entity("CinemaProject.Data.Hall", b =>
                {
                    b.Property<long>("HallId")
                        .HasColumnType("bigint")
                        .HasColumnName("hallId");

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cinemaId");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("format")
                        .IsFixedLength(true);

                    b.Property<string>("HallName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("hallName")
                        .IsFixedLength(true);

                    b.Property<long>("HallSeatsNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("hallSeatsNumber");

                    b.HasKey("HallId", "CinemaId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("CinemaProject.Data.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("cityId");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("district")
                        .IsFixedLength(true);

                    b.Property<string>("St")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("char(30)")
                        .HasColumnName("st")
                        .IsFixedLength(true);

                    b.HasKey("LocationId");

                    b.HasIndex("CityId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("CinemaProject.Data.Movie", b =>
                {
                    b.Property<long>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("movieId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int")
                        .HasColumnName("ageRestriction");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("createAt");

                    b.Property<string>("MovieDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("movieDescription")
                        .IsFixedLength(true);

                    b.Property<string>("MoviePhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moviePhotoPath");

                    b.Property<string>("MoviePreviewPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moviePreviewPath");

                    b.Property<string>("MovieTrailerPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("movieTrailerPath");

                    b.Property<string>("NameMovie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("nameMovie")
                        .IsFixedLength(true);

                    b.HasKey("MovieId");

                    b.ToTable("Movie");
                });

            modelBuilder.Entity("CinemaProject.Data.MovieRating", b =>
                {
                    b.Property<long>("MovieRattingtId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieRattingtId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieId");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("char(1000)")
                        .HasColumnName("comment")
                        .IsFixedLength(true);

                    b.Property<double>("Mark")
                        .HasColumnType("float")
                        .HasColumnName("mark");

                    b.HasKey("MovieRattingtId", "UserId", "MovieId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieRating");
                });

            modelBuilder.Entity("CinemaProject.Data.MovieSubcategory", b =>
                {
                    b.Property<long>("MovieSubcategoriesId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieSubcategoriesId");

                    b.Property<long>("SubcategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("subcategoryId");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieId");

                    b.HasKey("MovieSubcategoriesId", "SubcategoryId", "MovieId");

                    b.HasIndex("MovieId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("MovieSubcategories");
                });

            modelBuilder.Entity("CinemaProject.Data.Permission", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("permissionId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)")
                        .HasColumnName("permissionDescription")
                        .IsFixedLength(true);

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("permissionName")
                        .IsFixedLength(true);

                    b.HasKey("PermissionId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CinemaProject.Data.Product", b =>
                {
                    b.Property<long>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("productId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("char(50)")
                        .HasColumnName("productName")
                        .IsFixedLength(true);

                    b.Property<string>("ProductPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("productPrice");

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CinemaProject.Data.Promocode", b =>
                {
                    b.Property<long>("PromocodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("promocodeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountUse")
                        .HasColumnType("int")
                        .HasColumnName("countUse");

                    b.Property<string>("PromocodeDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("promocodeDescription")
                        .IsFixedLength(true);

                    b.Property<string>("PromocodeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("promocodeName")
                        .IsFixedLength(true);

                    b.HasKey("PromocodeId");

                    b.ToTable("Promocode");
                });

            modelBuilder.Entity("CinemaProject.Data.Reciept", b =>
                {
                    b.Property<long>("RecieptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("recieptId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .HasColumnName("paymentType")
                        .IsFixedLength(true);

                    b.Property<string>("TotalPrice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("totalPrice")
                        .IsFixedLength(true);

                    b.HasKey("RecieptId");

                    b.ToTable("Reciept");
                });

            modelBuilder.Entity("CinemaProject.Data.ReservedTicket", b =>
                {
                    b.Property<long>("ReservedTicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("reservedTicketId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ReservedTicketId");

                    b.ToTable("reservedTicket");
                });

            modelBuilder.Entity("CinemaProject.Data.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("roleDescription")
                        .IsFixedLength(true);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("roleName")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("CinemaProject.Data.Seat", b =>
                {
                    b.Property<long>("SeatId")
                        .HasColumnType("bigint")
                        .HasColumnName("seatId");

                    b.Property<long>("HallId")
                        .HasColumnType("bigint")
                        .HasColumnName("hallId");

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cinemaId");

                    b.Property<bool>("Class")
                        .HasColumnType("bit")
                        .HasColumnName("class");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int")
                        .HasColumnName("seatNumber");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int")
                        .HasColumnName("seatRow");

                    b.HasKey("SeatId", "HallId", "CinemaId");

                    b.HasIndex("HallId", "CinemaId");

                    b.HasIndex(new[] { "SeatId", "HallId" }, "FK_Seat")
                        .IsUnique();

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("CinemaProject.Data.Session", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sessionId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieId");

                    b.Property<long>("HallId")
                        .HasColumnType("bigint")
                        .HasColumnName("hallId");

                    b.Property<long>("DemonstrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("demonstrationId");

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("CinemaId");

                    b.Property<DateTime>("ScreenEnd")
                        .HasColumnType("date")
                        .HasColumnName("screenEnd");

                    b.Property<DateTime>("ScreenStart")
                        .HasColumnType("date")
                        .HasColumnName("screenStart");

                    b.HasKey("SessionId", "MovieId", "HallId", "DemonstrationId")
                        .HasName("PK_Session_1");

                    b.HasIndex("DemonstrationId");

                    b.HasIndex("MovieId");

                    b.HasIndex("HallId", "CinemaId");

                    b.ToTable("Session");
                });

            modelBuilder.Entity("CinemaProject.Data.Subcategory", b =>
                {
                    b.Property<long>("SubcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("subcategoryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("date")
                        .HasColumnName("createAt");

                    b.Property<string>("SubcategoryDescription")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .HasColumnName("subcategoryDescription")
                        .IsFixedLength(true);

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("char(20)")
                        .HasColumnName("subcategoryName")
                        .IsFixedLength(true);

                    b.HasKey("SubcategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategory");
                });

            modelBuilder.Entity("CinemaProject.Data.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticketId");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint")
                        .HasColumnName("seatId");

                    b.Property<long>("HallId")
                        .HasColumnType("bigint")
                        .HasColumnName("hallId");

                    b.Property<long>("SessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("sessionId");

                    b.Property<long>("MovieId")
                        .HasColumnType("bigint")
                        .HasColumnName("movieId");

                    b.Property<long>("CinemaId")
                        .HasColumnType("bigint")
                        .HasColumnName("cinemaId");

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cartId");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("userId");

                    b.Property<long>("DemonstrationId")
                        .HasColumnType("bigint")
                        .HasColumnName("demonstrationId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("createdAt");

                    b.Property<double>("TicketPrice")
                        .HasColumnType("float")
                        .HasColumnName("ticketPrice");

                    b.HasKey("TicketId", "SeatId", "HallId", "SessionId", "MovieId", "CinemaId", "CartId", "UserId", "DemonstrationId");

                    b.HasIndex("CartId", "UserId");

                    b.HasIndex("SeatId", "HallId");

                    b.HasIndex("SessionId", "MovieId", "HallId", "DemonstrationId");

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("CinemaProject.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("userEmail")
                        .IsFixedLength(true);

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nchar(256)")
                        .IsFixedLength(true);

                    b.Property<string>("UserPhone")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("userPassword")
                        .IsFixedLength(true);

                    b.Property<string>("UserSurname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("userSurname")
                        .IsFixedLength(true);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CinemaProject.Data.Cart", b =>
                {
                    b.HasOne("CinemaProject.Data.Promocode", "Promocode")
                        .WithMany("Carts")
                        .HasForeignKey("PromocodeId")
                        .HasConstraintName("FK_Cart_Promocode");

                    b.HasOne("CinemaProject.Data.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Cart_User")
                        .IsRequired();

                    b.Navigation("Promocode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaProject.Data.CartProduct", b =>
                {
                    b.HasOne("CinemaProject.Data.Product", "Product")
                        .WithMany("CartProducts")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_CartProducts_Product")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId", "UserId")
                        .HasConstraintName("FK_CartProducts_Cart")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CinemaProject.Data.Cinema", b =>
                {
                    b.HasOne("CinemaProject.Data.City", "City")
                        .WithMany("Cinemas")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Cinema_City")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CinemaProject.Data.Hall", b =>
                {
                    b.HasOne("CinemaProject.Data.Cinema", "Cinema")
                        .WithMany("Halls")
                        .HasForeignKey("CinemaId")
                        .HasConstraintName("FK_Hall_Cinema")
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("CinemaProject.Data.Location", b =>
                {
                    b.HasOne("CinemaProject.Data.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Location_City")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CinemaProject.Data.MovieRating", b =>
                {
                    b.HasOne("CinemaProject.Data.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_MovieRating_Movie")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.User", "User")
                        .WithMany("MovieRatings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_MovieRating_User")
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CinemaProject.Data.MovieSubcategory", b =>
                {
                    b.HasOne("CinemaProject.Data.Movie", "Movie")
                        .WithMany("MovieSubcategories")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_MovieSubcategories_Movie")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Subcategory", "Subcategory")
                        .WithMany("MovieSubcategories")
                        .HasForeignKey("SubcategoryId")
                        .HasConstraintName("FK_MovieSubcategories_Subcategory")
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("CinemaProject.Data.Seat", b =>
                {
                    b.HasOne("CinemaProject.Data.Hall", "Hall")
                        .WithMany("Seats")
                        .HasForeignKey("HallId", "CinemaId")
                        .HasConstraintName("FK_Seat_Hall")
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("CinemaProject.Data.Session", b =>
                {
                    b.HasOne("CinemaProject.Data.Demonstration", "Demonstration")
                        .WithMany("Sessions")
                        .HasForeignKey("DemonstrationId")
                        .HasConstraintName("FK_Session_Demonstration")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK_Session_Movie")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Hall", "Hall")
                        .WithMany("Sessions")
                        .HasForeignKey("HallId", "CinemaId")
                        .HasConstraintName("FK_Session_Hall")
                        .IsRequired();

                    b.Navigation("Demonstration");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CinemaProject.Data.Subcategory", b =>
                {
                    b.HasOne("CinemaProject.Data.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Subcategory_Category")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CinemaProject.Data.Ticket", b =>
                {
                    b.HasOne("CinemaProject.Data.Cart", "Cart")
                        .WithMany("Tickets")
                        .HasForeignKey("CartId", "UserId")
                        .HasConstraintName("FK_Ticket_Cart")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("SeatId", "HallId")
                        .HasConstraintName("FK_Ticket_Seat1")
                        .HasPrincipalKey("SeatId", "HallId")
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId", "MovieId", "HallId", "DemonstrationId")
                        .HasConstraintName("FK_Ticket_Session1")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("CinemaProject.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("CinemaProject.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("CinemaProject.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("CinemaProject.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaProject.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("CinemaProject.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaProject.Data.Cart", b =>
                {
                    b.Navigation("CartProducts");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaProject.Data.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("CinemaProject.Data.Cinema", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("CinemaProject.Data.City", b =>
                {
                    b.Navigation("Cinemas");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CinemaProject.Data.Demonstration", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaProject.Data.Hall", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaProject.Data.Movie", b =>
                {
                    b.Navigation("MovieRatings");

                    b.Navigation("MovieSubcategories");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaProject.Data.Product", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("CinemaProject.Data.Promocode", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("CinemaProject.Data.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaProject.Data.Session", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaProject.Data.Subcategory", b =>
                {
                    b.Navigation("MovieSubcategories");
                });

            modelBuilder.Entity("CinemaProject.Data.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("MovieRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
